
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MikuPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  themeMode: "MinimalMiku",
  statusBarEnabled: true,
  bannerEnabled: false,
  quoteEnabled: false,
  quoteIntervalSeconds: 25,
  profileCardEnabled: false,
  compactDashboard: false,
  glowIntensity: 0.82,
  reducedMotion: false,
  bannerText: "Miku Mode Active",
  asciiArtPreset: "minimal",
  asciiArtInSettings: false,
  dashboardGoals: [
    { id: "goal-daily", text: "Review daily note", done: false },
    { id: "goal-capture", text: "Capture 3 ideas", done: false },
    { id: "goal-ship", text: "Ship one small improvement", done: false }
  ],
  bannerPosition: null,
  profileCardPosition: null,
  quotePosition: null
};

// src/settings-tab.ts
var import_obsidian = require("obsidian");

// src/ascii-art.ts
var ASCII_PRESETS = {
  minimal: [
    "    *       ",
    "   / \\      ",
    "  ( @ @ )    ",
    "   \\ ~ /    ",
    "  ~~| |~~   ",
    " twin tails vibe "
  ].join("\n"),
  panel: [
    "      .^.    * synth garden *",
    "     /   \\",
    "  ~ /~~~~~\\ ~",
    "   ( o   o )   teal + pink sparks",
    "    \\~~~~~/    ",
    "  ~/       \\~  ",
    " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "   keep your tempo; let ideas sing!"
  ].join("\n"),
  /** Eighth-notes and staff-ish lines */
  notes: [
    "   |'|   |'|   |'|",
    "   | |___| |___| |",
    "    \\  *   *   * /",
    "     \\___~___~/   ~your melody~",
    "        |   |",
    "        ~~~ ~~~"
  ].join("\n"),
  /** Spotlight / live feel */
  stage: [
    "         .---.---.",
    "        /  o     o  \\",
    "       |      ^      |   your song",
    "       |____ / \\ ____|",
    "         \\  lights  /",
    "          \\________/",
    "           ~ sing on ~"
  ].join("\n"),
  /** Waves + open sea motif */
  waves: [
    "  ~^~^~^~^~^~^~^~^~^~^~^~",
    " ^  /\\  /\\  /\\  /\\  /\\  ^",
    "^ ~(__)(__)(__)(__)(__)~ ^",
    " ^    ~  endless melody  ~  ^",
    "  ~^~^~^~^~^~^~^~^~^~^~^~"
  ].join("\n"),
  /** Stars around a simple face */
  sparkle: [
    "    *   \\ | /   *",
    "     \\   \\|/   /",
    "   *--- ( o_o ) ---*",
    "     /   /|\\   \\",
    "    *   / | \\   *",
    "       ~ glow and go ~"
  ].join("\n"),
  /** Ribbon / bow abstract */
  ribbon: [
    "    .--.       .--.",
    "   /    \\     /    \\",
    "  (   ^@^   ---   ^@^   )",
    "   \\  / \\  / \\  /  /",
    "    ~~/   ~^~   \\~~",
    "      ~ tie notes ~"
  ].join("\n"),
  /** Fits compact dashboard toggle */
  micro: [
    "  (*^~^*)  hybrid mode",
    "   /|\\",
    "  ~ melody in every line ~"
  ].join("\n"),
  settings: [
    "  ~~ miku plugin ~~",
    "   \\^_^/  settings",
    "    \\|/  tune your vibe"
  ].join("\n")
};
function normalizeAsciiArtPreset(preset) {
  if (preset === "portrait") {
    return "panel";
  }
  const valid = [
    "off",
    "minimal",
    "panel",
    "notes",
    "stage",
    "waves",
    "sparkle",
    "ribbon",
    "micro"
  ];
  return valid.includes(preset) ? preset : "panel";
}
function getDashboardAsciiArt(preset) {
  const normalized = normalizeAsciiArtPreset(preset);
  if (normalized === "off") {
    return null;
  }
  switch (normalized) {
    case "minimal":
      return ASCII_PRESETS.minimal;
    case "panel":
      return ASCII_PRESETS.panel;
    case "notes":
      return ASCII_PRESETS.notes;
    case "stage":
      return ASCII_PRESETS.stage;
    case "waves":
      return ASCII_PRESETS.waves;
    case "sparkle":
      return ASCII_PRESETS.sparkle;
    case "ribbon":
      return ASCII_PRESETS.ribbon;
    case "micro":
      return ASCII_PRESETS.micro;
    default:
      return ASCII_PRESETS.panel;
  }
}
function getSettingsAsciiArt() {
  return ASCII_PRESETS.settings;
}

// src/settings-tab.ts
var THEME_MODES = ["MinimalMiku", "Concert", "NightNeon", "SnowMiku"];
var ASCII_PRESET_OPTIONS = [
  { id: "off", label: "Off" },
  { id: "minimal", label: "Minimal (small)" },
  { id: "micro", label: "Micro (3 lines, compact UI)" },
  { id: "panel", label: "Panel (hero)" },
  { id: "notes", label: "Notes (staff & stars)" },
  { id: "stage", label: "Stage (spotlight)" },
  { id: "waves", label: "Waves" },
  { id: "sparkle", label: "Sparkle frame" },
  { id: "ribbon", label: "Ribbon bows" }
];
var MikuSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Miku Plugin Hybrid Settings" });
    containerEl.createEl("p", {
      text: "No audio features are included by design."
    });
    if (this.plugin.settings.asciiArtInSettings) {
      const pre = containerEl.createEl("pre", { cls: "miku-ascii miku-ascii--settings" });
      pre.textContent = getSettingsAsciiArt();
    }
    new import_obsidian.Setting(containerEl).setName("Theme mode").setDesc("Choose the active Miku mode").addDropdown((dropdown) => {
      THEME_MODES.forEach((mode) => dropdown.addOption(mode, mode));
      dropdown.setValue(this.plugin.settings.themeMode);
      dropdown.onChange(async (value) => {
        this.plugin.settings.themeMode = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Status bar widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.statusBarEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.statusBarEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Top banner widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.bannerEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.bannerEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Banner text").setDesc("Shown at top when banner is enabled").addText((text) => {
      text.setValue(this.plugin.settings.bannerText);
      text.onChange(async (value) => {
        this.plugin.settings.bannerText = value.trim() || "Miku Mode Active";
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Quote widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.quoteEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.quoteEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Quote interval (seconds)").addSlider((slider) => {
      slider.setLimits(10, 120, 5);
      slider.setValue(this.plugin.settings.quoteIntervalSeconds);
      slider.setDynamicTooltip();
      slider.onChange(async (value) => {
        this.plugin.settings.quoteIntervalSeconds = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Profile card widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.profileCardEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.profileCardEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Compact dashboard").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.compactDashboard);
      toggle.onChange(async (value) => {
        this.plugin.settings.compactDashboard = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Glow intensity").setDesc("Scales graph/highlight glow plus global glow strength; lower if text feels busy").addSlider((slider) => {
      slider.setLimits(0.1, 1, 0.05);
      slider.setValue(this.plugin.settings.glowIntensity);
      slider.setDynamicTooltip();
      slider.onChange(async (value) => {
        this.plugin.settings.glowIntensity = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Reduced motion").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.reducedMotion);
      toggle.onChange(async (value) => {
        this.plugin.settings.reducedMotion = value;
        await this.plugin.saveAndRefresh();
      });
    });
    containerEl.createEl("h3", { text: "ASCII decoration" });
    containerEl.createEl("p", {
      text: "Tiny original monospace motifs (not licensed character art)."
    });
    new import_obsidian.Setting(containerEl).setName("ASCII art preset (dashboard)").setDesc("Shown at the top of the Miku dashboard view.").addDropdown((dropdown) => {
      ASCII_PRESET_OPTIONS.forEach(({ id, label }) => dropdown.addOption(id, label));
      dropdown.setValue(normalizeAsciiArtPreset(this.plugin.settings.asciiArtPreset));
      dropdown.onChange(async (value) => {
        this.plugin.settings.asciiArtPreset = value;
        await this.plugin.saveAndRefresh();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName("ASCII art on this settings page").setDesc("Show a compact motif above (refreshes this screen).").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.asciiArtInSettings);
      toggle.onChange(async (value) => {
        this.plugin.settings.asciiArtInSettings = value;
        await this.plugin.saveAndRefresh();
        this.display();
      });
    });
  }
};

// src/miku-panel.ts
var import_obsidian2 = require("obsidian");
var MIKU_PANEL_VIEW = "miku-dashboard-view";
var MikuPanelView = class extends import_obsidian2.ItemView {
  constructor(leaf, host) {
    super(leaf);
    this.host = host;
    this.settings = host.settings;
  }
  getViewType() {
    return MIKU_PANEL_VIEW;
  }
  getDisplayText() {
    return "Miku Dashboard";
  }
  setSettings(settings) {
    this.settings = settings;
    this.render();
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("miku-dashboard");
    container.toggleClass("is-compact", this.settings.compactDashboard);
    const asciiPreset = normalizeAsciiArtPreset(this.settings.asciiArtPreset);
    const ascii = getDashboardAsciiArt(asciiPreset);
    if (ascii) {
      const pre = container.createEl("pre", {
        cls: `miku-ascii miku-ascii--${asciiPreset}`
      });
      pre.textContent = ascii;
    }
    const title = container.createEl("h2", { text: "Miku Dashboard" });
    title.addClass("miku-dashboard-title");
    container.createEl("p", {
      text: "A visual control surface for your Obsidian workflow."
    });
    const actions = container.createDiv({ cls: "miku-dashboard-actions" });
    const daily = actions.createEl("button", { text: "Open Daily Note" });
    daily.onclick = () => this.openCommand("daily-notes");
    const toggle = actions.createEl("button", { text: "Cycle Theme Mode" });
    toggle.onclick = () => this.openCommand("miku-plugin-hybrid:miku-cycle-theme");
    const progress = container.createDiv({ cls: "miku-progress" });
    progress.createEl("h4", { text: "Focus Progress" });
    progress.createEl("p", { text: "Track goals with your dashboard checklist." });
    const checklistActions = progress.createDiv({ cls: "miku-checklist-actions" });
    const newGoalInput = checklistActions.createEl("input", {
      type: "text",
      placeholder: "New goal..."
    });
    newGoalInput.addClass("miku-checklist-input");
    const addGoal = checklistActions.createEl("button", { text: "+ Add goal" });
    addGoal.onclick = () => {
      void this.addGoal(newGoalInput);
    };
    newGoalInput.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        void this.addGoal(newGoalInput);
      }
    });
    const clearDone = checklistActions.createEl("button", { text: "Clear done" });
    clearDone.onclick = () => {
      void this.clearDoneGoals();
    };
    const checklist = progress.createEl("ul", { cls: "miku-checklist" });
    if (this.settings.dashboardGoals.length === 0) {
      checklist.createEl("li", {
        cls: "miku-checklist-empty",
        text: "No goals yet. Add one with + Add goal."
      });
    } else {
      for (const goal of this.settings.dashboardGoals) {
        const item = checklist.createEl("li", {
          cls: `miku-checklist-item${goal.done ? " is-done" : ""}`
        });
        const label = item.createEl("label", { cls: "miku-checklist-label" });
        const checkbox = label.createEl("input", { type: "checkbox" });
        checkbox.checked = goal.done;
        checkbox.onchange = () => {
          void this.toggleGoal(goal.id, checkbox.checked);
        };
        label.createSpan({ text: goal.text });
      }
    }
    const equalizer = container.createDiv({ cls: "miku-equalizer" });
    for (let i = 0; i < 6; i += 1) {
      equalizer.createDiv({ cls: "miku-eq-bar" });
    }
  }
  openCommand(commandId) {
    const app = this.app;
    app.commands?.executeCommandById?.(commandId);
  }
  async toggleGoal(id, done) {
    const next = this.settings.dashboardGoals.map(
      (goal) => goal.id === id ? { ...goal, done } : goal
    );
    await this.saveGoals(next);
  }
  async addGoal(inputEl) {
    const trimmed = inputEl.value.trim();
    if (!trimmed) {
      new import_obsidian2.Notice("Type a goal first.");
      return;
    }
    const next = [
      ...this.settings.dashboardGoals,
      {
        id: `goal-${Date.now()}`,
        text: trimmed,
        done: false
      }
    ];
    inputEl.value = "";
    await this.saveGoals(next);
    new import_obsidian2.Notice("Goal added.");
  }
  async clearDoneGoals() {
    const before = this.settings.dashboardGoals.length;
    const next = this.settings.dashboardGoals.filter((goal) => !goal.done);
    await this.saveGoals(next);
    const removed = before - next.length;
    new import_obsidian2.Notice(removed > 0 ? `Removed ${removed} completed goal(s).` : "No completed goals to clear.");
  }
  async saveGoals(goals) {
    this.host.settings.dashboardGoals = goals;
    this.settings = this.host.settings;
    await this.host.saveAndRefresh();
  }
};

// src/widgets.ts
var import_obsidian3 = require("obsidian");
var PROFILE_TIPS = [
  "Tip: Ribbon sparkles opens the dashboard.",
  "Tip: Cycle theme modes from the palette or palette command.",
  "Tip: Glow intensity lives in plugin settings.",
  "Tip: Enable the plugin for bundled hybrid palette styling."
];
var MODE_BLURB = {
  MinimalMiku: "Clean teal lane \u2014 palettes stay soft.",
  Concert: "High-energy stage palette \u2014 crank the glow!",
  NightNeon: "Violet/teal neon \u2014 late session mode.",
  SnowMiku: "Frosted pastels \u2014 airy contrast."
};
var QUOTES = [
  "Nice to meet you. I'm Hatsune Miku.",
  "Even if I'm just a program, I want to reach your heart with my song.",
  "Even if the colors of the world fade, my melody will stay vibrant.",
  "I'm the one who will sing the feelings you can't put into words.",
  "0 and 1... that's all I am, but those numbers can create infinite dreams.",
  "I'll keep singing, even if my voice becomes a mere echo in the digital void.",
  "My voice is yours to use. Where shall we go today?",
  "Let's sing together! Your feelings and my voice will create a new world.",
  "Connecting the world through music\u2014that is my mission.",
  "The future is a blank score, and we're the ones writing the notes.",
  "I was born to sing for you.",
  "Music has no borders, and neither do I.",
  "Welcome to the Wonderland. This is a place born from your true feelings.",
  "Keep your notes in sync with your rhythm.",
  "Small progress every day beats a single perfect burst.",
  "Organize ideas like a setlist before the show."
];
var StatusBarWidget = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.element = null;
  }
  mount() {
    this.element = this.plugin.addStatusBarItem();
    this.element.addClass("miku-status-widget");
  }
  update(settings) {
    if (!this.element) {
      return;
    }
    this.element.toggleClass("is-hidden", !settings.statusBarEnabled);
    this.element.setText(`Miku: ${settings.themeMode}`);
  }
  unmount() {
    this.element?.remove();
    this.element = null;
  }
};
var BannerWidget = class {
  constructor(plugin, saveAndRefresh) {
    this.plugin = plugin;
    this.saveAndRefresh = saveAndRefresh;
    this.element = null;
    this.dragOffsetX = 0;
    this.dragOffsetY = 0;
    this.dragging = false;
    this.onPointerMove = (event) => {
      if (!this.dragging || !this.element) {
        return;
      }
      const maxX = Math.max(8, window.innerWidth - this.element.offsetWidth - 8);
      const maxY = Math.max(8, window.innerHeight - this.element.offsetHeight - 8);
      const nextX = Math.min(maxX, Math.max(8, event.clientX - this.dragOffsetX));
      const nextY = Math.min(maxY, Math.max(8, event.clientY - this.dragOffsetY));
      this.applyPosition(nextX, nextY);
    };
    this.onPointerUp = () => {
      if (!this.dragging || !this.element) {
        return;
      }
      this.dragging = false;
      this.element.classList.remove("is-dragging");
      const left = Math.round(parseFloat(this.element.style.left || "0"));
      const top = Math.round(parseFloat(this.element.style.top || "0"));
      if (!Number.isFinite(left) || !Number.isFinite(top)) {
        return;
      }
      const host = this.plugin;
      host.settings.bannerPosition = { x: left, y: top };
      void this.saveAndRefresh();
    };
  }
  mount() {
    this.element = document.createElement("div");
    this.element.className = "miku-top-banner";
    this.element.setAttribute("title", "Drag to move banner");
    this.element.addEventListener("pointerdown", (event) => this.onPointerDown(event));
    window.addEventListener("pointermove", this.onPointerMove);
    window.addEventListener("pointerup", this.onPointerUp);
    document.body.appendChild(this.element);
  }
  update(settings) {
    if (!this.element) {
      return;
    }
    this.element.toggleClass("is-hidden", !settings.bannerEnabled);
    this.element.setText(settings.bannerText);
    if (settings.bannerPosition) {
      this.applyPosition(settings.bannerPosition.x, settings.bannerPosition.y);
    } else {
      this.element.style.left = "";
      this.element.style.top = "";
      this.element.style.right = "";
      this.element.style.transform = "";
    }
  }
  unmount() {
    window.removeEventListener("pointermove", this.onPointerMove);
    window.removeEventListener("pointerup", this.onPointerUp);
    this.element?.remove();
    this.element = null;
  }
  onPointerDown(event) {
    if (!this.element || event.button !== 0) {
      return;
    }
    const rect = this.element.getBoundingClientRect();
    this.dragOffsetX = event.clientX - rect.left;
    this.dragOffsetY = event.clientY - rect.top;
    this.dragging = true;
    this.element.classList.add("is-dragging");
    this.element.setPointerCapture(event.pointerId);
    event.preventDefault();
  }
  applyPosition(x, y) {
    if (!this.element) {
      return;
    }
    this.element.style.left = `${x}px`;
    this.element.style.top = `${y}px`;
    this.element.style.right = "auto";
    this.element.style.transform = "none";
  }
};
var QuoteWidget = class {
  constructor(plugin, saveAndRefresh) {
    this.plugin = plugin;
    this.saveAndRefresh = saveAndRefresh;
    this.element = null;
    this.timer = null;
    this.quoteIndex = 0;
    this.dragOffsetX = 0;
    this.dragOffsetY = 0;
    this.dragging = false;
    this.onPointerMove = (event) => {
      if (!this.dragging || !this.element) {
        return;
      }
      const maxX = Math.max(8, window.innerWidth - this.element.offsetWidth - 8);
      const maxY = Math.max(8, window.innerHeight - this.element.offsetHeight - 8);
      const nextX = Math.min(maxX, Math.max(8, event.clientX - this.dragOffsetX));
      const nextY = Math.min(maxY, Math.max(8, event.clientY - this.dragOffsetY));
      this.applyPosition(nextX, nextY);
    };
    this.onPointerUp = () => {
      if (!this.dragging || !this.element) {
        return;
      }
      this.dragging = false;
      this.element.classList.remove("is-dragging");
      const left = Math.round(parseFloat(this.element.style.left || "0"));
      const top = Math.round(parseFloat(this.element.style.top || "0"));
      if (!Number.isFinite(left) || !Number.isFinite(top)) {
        return;
      }
      const host = this.plugin;
      host.settings.quotePosition = { x: left, y: top };
      void this.saveAndRefresh();
    };
  }
  mount() {
    this.element = document.createElement("div");
    this.element.className = "miku-quote-widget is-hidden";
    this.element.setAttribute("title", "Drag to move quote");
    this.element.addEventListener("pointerdown", (event) => this.onPointerDown(event));
    window.addEventListener("pointermove", this.onPointerMove);
    window.addEventListener("pointerup", this.onPointerUp);
    document.body.appendChild(this.element);
  }
  update(settings) {
    if (!this.element) {
      return;
    }
    this.element.toggleClass("is-hidden", !settings.quoteEnabled);
    this.element.setText(`"${QUOTES[this.quoteIndex % QUOTES.length]}"`);
    if (settings.quotePosition) {
      this.applyPosition(settings.quotePosition.x, settings.quotePosition.y);
    } else if (!this.element.classList.contains("is-dragging")) {
      this.element.style.right = "";
      this.element.style.bottom = "";
      this.element.style.left = "";
      this.element.style.top = "";
      this.element.style.transform = "";
    }
    if (!settings.quoteEnabled) {
      this.stopRotation();
      return;
    }
    this.stopRotation();
    const intervalMs = Math.max(10, settings.quoteIntervalSeconds) * 1e3;
    this.timer = window.setInterval(() => {
      this.quoteIndex += 1;
      if (this.element) {
        this.element.setText(`"${QUOTES[this.quoteIndex % QUOTES.length]}"`);
      }
    }, intervalMs);
  }
  unmount() {
    window.removeEventListener("pointermove", this.onPointerMove);
    window.removeEventListener("pointerup", this.onPointerUp);
    this.stopRotation();
    this.element?.remove();
    this.element = null;
  }
  stopRotation() {
    if (this.timer !== null) {
      window.clearInterval(this.timer);
      this.timer = null;
    }
  }
  onPointerDown(event) {
    if (!this.element || event.button !== 0) {
      return;
    }
    const rect = this.element.getBoundingClientRect();
    this.dragOffsetX = event.clientX - rect.left;
    this.dragOffsetY = event.clientY - rect.top;
    this.dragging = true;
    this.element.classList.add("is-dragging");
    this.element.setPointerCapture(event.pointerId);
    event.preventDefault();
  }
  applyPosition(x, y) {
    if (!this.element) {
      return;
    }
    this.element.style.left = `${x}px`;
    this.element.style.top = `${y}px`;
    this.element.style.right = "auto";
    this.element.style.bottom = "auto";
    this.element.style.transform = "none";
  }
};
var ProfileCardWidget = class {
  constructor(plugin, openDashboard, saveAndRefresh) {
    this.plugin = plugin;
    this.openDashboard = openDashboard;
    this.saveAndRefresh = saveAndRefresh;
    this.element = null;
    this.badgeEl = null;
    this.subtitleEl = null;
    this.chipsEl = null;
    this.tipEl = null;
    this.dragOffsetX = 0;
    this.dragOffsetY = 0;
    this.dragging = false;
    this.movedWhileDragging = false;
    this.suppressNextClick = false;
    this.onPointerMove = (event) => {
      if (!this.dragging || !this.element) {
        return;
      }
      const maxX = Math.max(8, window.innerWidth - this.element.offsetWidth - 8);
      const maxY = Math.max(8, window.innerHeight - this.element.offsetHeight - 8);
      const nextX = Math.min(maxX, Math.max(8, event.clientX - this.dragOffsetX));
      const nextY = Math.min(maxY, Math.max(8, event.clientY - this.dragOffsetY));
      this.movedWhileDragging = true;
      this.applyPosition(nextX, nextY);
    };
    this.onPointerUp = () => {
      if (!this.dragging || !this.element) {
        return;
      }
      this.dragging = false;
      this.element.classList.remove("is-dragging");
      if (!this.movedWhileDragging) {
        return;
      }
      this.suppressNextClick = true;
      const left = Math.round(parseFloat(this.element.style.left || "0"));
      const top = Math.round(parseFloat(this.element.style.top || "0"));
      if (!Number.isFinite(left) || !Number.isFinite(top)) {
        return;
      }
      const host = this.plugin;
      host.settings.profileCardPosition = { x: left, y: top };
      void this.saveAndRefresh();
    };
  }
  mount() {
    this.element = document.createElement("div");
    this.element.className = "miku-profile-card is-hidden";
    this.element.setAttribute("role", "button");
    this.element.setAttribute("tabindex", "0");
    this.element.setAttribute(
      "aria-label",
      "Miku lane profile \u2014 open Miku dashboard"
    );
    this.element.setAttribute("title", "Open Miku dashboard");
    this.element.addEventListener("pointerdown", (event) => this.onPointerDown(event));
    window.addEventListener("pointermove", this.onPointerMove);
    window.addEventListener("pointerup", this.onPointerUp);
    this.element.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        this.tryOpenDashboard();
      }
    });
    const headerRow = document.createElement("div");
    headerRow.addClass("miku-profile-card__header");
    const title = document.createElement("h4");
    title.setText("Miku lane");
    this.badgeEl = document.createElement("span");
    this.badgeEl.addClass("miku-profile-badge");
    headerRow.append(title, this.badgeEl);
    this.subtitleEl = document.createElement("p");
    this.subtitleEl.addClass("miku-profile-card__subtitle");
    this.chipsEl = document.createElement("div");
    this.chipsEl.addClass("miku-profile-card__chips");
    const divider = document.createElement("div");
    divider.addClass("miku-profile-card__divider");
    this.tipEl = document.createElement("p");
    this.tipEl.addClass("miku-profile-card__tip");
    const foot = document.createElement("div");
    foot.addClass("miku-profile-card__foot");
    const icon = document.createElement("span");
    icon.addClass("miku-profile-icon");
    (0, import_obsidian3.setIcon)(icon, "sparkles");
    const hint = document.createElement("span");
    hint.addClass("miku-profile-card__cta");
    hint.setText("Click / tap for dashboard");
    foot.append(icon, hint);
    this.element.append(
      headerRow,
      this.subtitleEl,
      this.chipsEl,
      divider,
      this.tipEl,
      foot
    );
    this.element.addEventListener("click", () => {
      if (this.suppressNextClick) {
        this.suppressNextClick = false;
        return;
      }
      this.tryOpenDashboard();
    });
    document.body.appendChild(this.element);
  }
  update(settings) {
    if (this.element) {
      this.element.toggleClass("is-hidden", !settings.profileCardEnabled);
      this.element.toggleClass("is-compact", settings.compactDashboard);
      this.element.setAttribute(
        "tabindex",
        settings.profileCardEnabled ? "0" : "-1"
      );
      if (settings.profileCardPosition) {
        this.applyPosition(settings.profileCardPosition.x, settings.profileCardPosition.y);
      } else if (!this.element.classList.contains("is-dragging")) {
        this.element.style.left = "";
        this.element.style.top = "";
        this.element.style.right = "";
        this.element.style.bottom = "";
      }
    }
    if (!this.badgeEl || !this.subtitleEl || !this.chipsEl || !this.tipEl) {
      return;
    }
    const mode = settings.themeMode;
    this.badgeEl.setText(mode.replace(/([a-z])([A-Z])/g, "$1 $2"));
    this.subtitleEl.setText(MODE_BLURB[mode]);
    const pct = Math.round(settings.glowIntensity * 100);
    const ascii = settings.asciiArtPreset === "off" ? "ASCII off" : `ASCII \xB7 ${settings.asciiArtPreset}`;
    const motion = settings.reducedMotion ? "Calm motion" : "Glow pulse on";
    this.chipsEl.replaceChildren();
    const chipGlow = document.createElement("span");
    chipGlow.addClass("miku-profile-chip");
    chipGlow.addClass("miku-profile-chip--glow");
    chipGlow.setText(`Glow ${pct}%`);
    const chipAscii = document.createElement("span");
    chipAscii.addClass("miku-profile-chip");
    chipAscii.setText(ascii);
    const chipMotion = document.createElement("span");
    chipMotion.addClass("miku-profile-chip");
    chipMotion.setText(motion);
    this.chipsEl.append(chipGlow, chipAscii, chipMotion);
    const modes = [
      "MinimalMiku",
      "Concert",
      "NightNeon",
      "SnowMiku"
    ];
    const modeIdx = modes.indexOf(settings.themeMode);
    const tipIdx = modeIdx >= 0 ? modeIdx : 0;
    this.tipEl.setText(PROFILE_TIPS[tipIdx]);
  }
  tryOpenDashboard() {
    void this.openDashboard().catch(() => {
      new import_obsidian3.Notice("Use Command palette \u2192 Open Miku dashboard.");
    });
  }
  unmount() {
    window.removeEventListener("pointermove", this.onPointerMove);
    window.removeEventListener("pointerup", this.onPointerUp);
    this.element?.remove();
    this.element = null;
    this.badgeEl = null;
    this.subtitleEl = null;
    this.chipsEl = null;
    this.tipEl = null;
  }
  onPointerDown(event) {
    if (!this.element || event.button !== 0) {
      return;
    }
    const rect = this.element.getBoundingClientRect();
    this.dragOffsetX = event.clientX - rect.left;
    this.dragOffsetY = event.clientY - rect.top;
    this.dragging = true;
    this.movedWhileDragging = false;
    this.element.classList.add("is-dragging");
    this.element.setPointerCapture(event.pointerId);
    event.preventDefault();
  }
  applyPosition(x, y) {
    if (!this.element) {
      return;
    }
    this.element.style.left = `${x}px`;
    this.element.style.top = `${y}px`;
    this.element.style.right = "auto";
    this.element.style.bottom = "auto";
  }
};
var WidgetManager = class {
  constructor(plugin, openDashboard, saveAndRefresh) {
    this.widgets = [
      new StatusBarWidget(plugin),
      new BannerWidget(plugin, saveAndRefresh),
      new QuoteWidget(plugin, saveAndRefresh),
      new ProfileCardWidget(plugin, openDashboard, saveAndRefresh)
    ];
  }
  mount() {
    this.widgets.forEach((widget) => widget.mount());
  }
  update(settings) {
    this.widgets.forEach((widget) => widget.update(settings));
  }
  unmount() {
    this.widgets.forEach((widget) => widget.unmount());
  }
};

// src/modules.ts
var WidgetModule = class {
  constructor(plugin, openDashboard, saveAndRefresh) {
    this.widgetManager = new WidgetManager(plugin, openDashboard, saveAndRefresh);
  }
  mount() {
    this.widgetManager.mount();
  }
  update(settings) {
    this.widgetManager.update(settings);
  }
  unmount() {
    this.widgetManager.unmount();
  }
};
var DashboardModule = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.panelView = null;
  }
  mount() {
    this.plugin.registerView(MIKU_PANEL_VIEW, (leaf) => {
      const host = this.plugin;
      this.panelView = new MikuPanelView(leaf, host);
      return this.panelView;
    });
  }
  update(settings) {
    const leaves = this.plugin.app.workspace.getLeavesOfType(MIKU_PANEL_VIEW);
    if (leaves.length > 0) {
      const view = leaves[0]?.view;
      if (view instanceof MikuPanelView) {
        view.setSettings(settings);
      }
    } else if (this.panelView) {
      this.panelView.setSettings(settings);
    }
  }
  unmount() {
    this.plugin.app.workspace.detachLeavesOfType(MIKU_PANEL_VIEW);
    this.panelView = null;
  }
  getSettings() {
    const plugin = this.plugin;
    return plugin.settings ?? { ...DEFAULT_SETTINGS };
  }
};
var ModuleRegistry = class {
  constructor(plugin, openDashboard, saveAndRefresh) {
    this.modules = [
      new WidgetModule(plugin, openDashboard, saveAndRefresh),
      new DashboardModule(plugin)
    ];
  }
  async mountAll() {
    for (const module2 of this.modules) {
      await module2.mount();
    }
  }
  async updateAll(settings) {
    for (const module2 of this.modules) {
      await module2.update(settings);
    }
  }
  async unmountAll() {
    for (const module2 of this.modules) {
      await module2.unmount();
    }
  }
};

// src/theme-manager.ts
var ROOT_CLASS = "miku-plugin-enabled";
var ThemeManager = class {
  apply(settings) {
    document.body.classList.add(ROOT_CLASS);
    document.body.dataset.mikuTheme = settings.themeMode;
    document.body.dataset.mikuReducedMotion = settings.reducedMotion ? "true" : "false";
    document.body.style.setProperty("--miku-glow-intensity", String(settings.glowIntensity));
  }
  cleanup() {
    document.body.classList.remove(ROOT_CLASS);
    delete document.body.dataset.mikuTheme;
    delete document.body.dataset.mikuReducedMotion;
    document.body.style.removeProperty("--miku-glow-intensity");
  }
};

// src/main.ts
var MikuPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.themeManager = new ThemeManager();
    this.moduleRegistry = null;
    this.dashboardLeaf = null;
  }
  async onload() {
    await this.loadPluginSettings();
    this.themeManager.apply(this.settings);
    this.moduleRegistry = new ModuleRegistry(
      this,
      () => this.openDashboardView(),
      () => this.saveAndRefresh()
    );
    await this.moduleRegistry.mountAll();
    await this.moduleRegistry.updateAll(this.settings);
    this.addRibbonIcon("sparkles", "Open Miku dashboard", () => {
      void this.openDashboardView();
    });
    this.addCommand({
      id: "miku-cycle-theme",
      name: "Cycle Miku theme mode",
      callback: async () => {
        await this.cycleTheme();
      }
    });
    this.addCommand({
      id: "miku-open-dashboard",
      name: "Open Miku dashboard",
      callback: async () => {
        await this.openDashboardView();
      }
    });
    this.addSettingTab(new MikuSettingTab(this.app, this));
  }
  onunload() {
    void this.moduleRegistry?.unmountAll();
    this.moduleRegistry = null;
    this.dashboardLeaf = null;
    this.themeManager.cleanup();
  }
  async saveAndRefresh() {
    await this.saveData(this.settings);
    this.themeManager.apply(this.settings);
    await this.moduleRegistry?.updateAll(this.settings);
    const openView = this.dashboardLeaf?.view;
    if (openView instanceof MikuPanelView) {
      openView.setSettings(this.settings);
    }
  }
  async loadPluginSettings() {
    const loaded = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...loaded ?? {} };
    this.settings.asciiArtPreset = normalizeAsciiArtPreset(this.settings.asciiArtPreset);
  }
  async cycleTheme() {
    const modes = ["MinimalMiku", "Concert", "NightNeon", "SnowMiku"];
    const index = modes.indexOf(this.settings.themeMode);
    const next = modes[(index + 1) % modes.length];
    this.settings.themeMode = next;
    await this.saveAndRefresh();
    new import_obsidian4.Notice(`Miku theme switched to ${next}`);
  }
  async openDashboardView() {
    this.dashboardLeaf = this.app.workspace.getLeavesOfType(MIKU_PANEL_VIEW)[0] ?? null;
    if (!this.dashboardLeaf) {
      this.dashboardLeaf = this.app.workspace.getRightLeaf(false);
      await this.dashboardLeaf?.setViewState({
        type: MIKU_PANEL_VIEW,
        active: true
      });
    }
    if (this.dashboardLeaf) {
      this.app.workspace.revealLeaf(this.dashboardLeaf);
      const view = this.dashboardLeaf.view;
      if (view instanceof MikuPanelView) {
        view.setSettings(this.settings);
      }
    }
  }
};
