
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MikuPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  themeMode: "MinimalMiku",
  statusBarEnabled: true,
  bannerEnabled: false,
  quoteEnabled: false,
  quoteIntervalSeconds: 25,
  profileCardEnabled: false,
  compactDashboard: false,
  glowIntensity: 0.55,
  reducedMotion: false,
  bannerText: "Miku Mode Active"
};

// src/settings-tab.ts
var import_obsidian = require("obsidian");
var THEME_MODES = ["MinimalMiku", "Concert", "NightNeon", "SnowMiku"];
var MikuSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Miku Plugin Hybrid Settings" });
    containerEl.createEl("p", {
      text: "No audio features are included by design."
    });
    new import_obsidian.Setting(containerEl).setName("Theme mode").setDesc("Choose the active Miku mode").addDropdown((dropdown) => {
      THEME_MODES.forEach((mode) => dropdown.addOption(mode, mode));
      dropdown.setValue(this.plugin.settings.themeMode);
      dropdown.onChange(async (value) => {
        this.plugin.settings.themeMode = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Status bar widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.statusBarEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.statusBarEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Top banner widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.bannerEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.bannerEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Banner text").setDesc("Shown at top when banner is enabled").addText((text) => {
      text.setValue(this.plugin.settings.bannerText);
      text.onChange(async (value) => {
        this.plugin.settings.bannerText = value.trim() || "Miku Mode Active";
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Quote widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.quoteEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.quoteEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Quote interval (seconds)").addSlider((slider) => {
      slider.setLimits(10, 120, 5);
      slider.setValue(this.plugin.settings.quoteIntervalSeconds);
      slider.setDynamicTooltip();
      slider.onChange(async (value) => {
        this.plugin.settings.quoteIntervalSeconds = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Profile card widget").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.profileCardEnabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.profileCardEnabled = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Compact dashboard").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.compactDashboard);
      toggle.onChange(async (value) => {
        this.plugin.settings.compactDashboard = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Glow intensity").setDesc("Keep this subtle for readability").addSlider((slider) => {
      slider.setLimits(0.1, 1, 0.05);
      slider.setValue(this.plugin.settings.glowIntensity);
      slider.setDynamicTooltip();
      slider.onChange(async (value) => {
        this.plugin.settings.glowIntensity = value;
        await this.plugin.saveAndRefresh();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Reduced motion").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.reducedMotion);
      toggle.onChange(async (value) => {
        this.plugin.settings.reducedMotion = value;
        await this.plugin.saveAndRefresh();
      });
    });
  }
};

// src/miku-panel.ts
var import_obsidian2 = require("obsidian");
var MIKU_PANEL_VIEW = "miku-dashboard-view";
var MikuPanelView = class extends import_obsidian2.ItemView {
  constructor(leaf, settings) {
    super(leaf);
    this.settings = settings;
  }
  getViewType() {
    return MIKU_PANEL_VIEW;
  }
  getDisplayText() {
    return "Miku Dashboard";
  }
  setSettings(settings) {
    this.settings = settings;
    this.render();
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("miku-dashboard");
    container.toggleClass("is-compact", this.settings.compactDashboard);
    const title = container.createEl("h2", { text: "Miku Dashboard" });
    title.addClass("miku-dashboard-title");
    container.createEl("p", {
      text: "A visual control surface for your Obsidian workflow."
    });
    const actions = container.createDiv({ cls: "miku-dashboard-actions" });
    const daily = actions.createEl("button", { text: "Open Daily Note" });
    daily.onclick = () => this.openCommand("daily-notes");
    const toggle = actions.createEl("button", { text: "Cycle Theme Mode" });
    toggle.onclick = () => this.openCommand("miku-plugin-hybrid:miku-cycle-theme");
    const progress = container.createDiv({ cls: "miku-progress" });
    progress.createEl("h4", { text: "Focus Progress" });
    progress.createEl("p", { text: "Track goals with checklist and daily note links." });
    const equalizer = container.createDiv({ cls: "miku-equalizer" });
    for (let i = 0; i < 6; i += 1) {
      equalizer.createDiv({ cls: "miku-eq-bar" });
    }
  }
  openCommand(commandId) {
    const app = this.app;
    app.commands?.executeCommandById?.(commandId);
  }
};

// src/widgets.ts
var import_obsidian3 = require("obsidian");
var QUOTES = [
  "Keep your notes in sync with your rhythm.",
  "Small progress every day beats a single perfect burst.",
  "Organize ideas like a setlist before the show.",
  "Create first, polish second, ship always."
];
var StatusBarWidget = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.element = null;
  }
  mount() {
    this.element = this.plugin.addStatusBarItem();
    this.element.addClass("miku-status-widget");
  }
  update(settings) {
    if (!this.element) {
      return;
    }
    this.element.toggleClass("is-hidden", !settings.statusBarEnabled);
    this.element.setText(`Miku: ${settings.themeMode}`);
  }
  unmount() {
    this.element?.remove();
    this.element = null;
  }
};
var BannerWidget = class {
  constructor() {
    this.element = null;
  }
  mount() {
    this.element = document.createElement("div");
    this.element.className = "miku-top-banner";
    document.body.appendChild(this.element);
  }
  update(settings) {
    if (!this.element) {
      return;
    }
    this.element.toggleClass("is-hidden", !settings.bannerEnabled);
    this.element.setText(settings.bannerText);
  }
  unmount() {
    this.element?.remove();
    this.element = null;
  }
};
var QuoteWidget = class {
  constructor() {
    this.element = null;
    this.timer = null;
    this.quoteIndex = 0;
  }
  mount() {
    this.element = document.createElement("div");
    this.element.className = "miku-quote-widget is-hidden";
    document.body.appendChild(this.element);
  }
  update(settings) {
    if (!this.element) {
      return;
    }
    this.element.toggleClass("is-hidden", !settings.quoteEnabled);
    this.element.setText(`"${QUOTES[this.quoteIndex % QUOTES.length]}"`);
    if (!settings.quoteEnabled) {
      this.stopRotation();
      return;
    }
    this.stopRotation();
    const intervalMs = Math.max(10, settings.quoteIntervalSeconds) * 1e3;
    this.timer = window.setInterval(() => {
      this.quoteIndex += 1;
      if (this.element) {
        this.element.setText(`"${QUOTES[this.quoteIndex % QUOTES.length]}"`);
      }
    }, intervalMs);
  }
  unmount() {
    this.stopRotation();
    this.element?.remove();
    this.element = null;
  }
  stopRotation() {
    if (this.timer !== null) {
      window.clearInterval(this.timer);
      this.timer = null;
    }
  }
};
var ProfileCardWidget = class {
  constructor() {
    this.element = null;
  }
  mount() {
    this.element = document.createElement("div");
    this.element.className = "miku-profile-card is-hidden";
    const title = document.createElement("h4");
    title.setText("Miku Assistant");
    const detail = document.createElement("p");
    detail.setText("Theme and workflow widgets are active.");
    this.element.append(title, detail);
    const icon = document.createElement("span");
    icon.addClass("miku-profile-icon");
    (0, import_obsidian3.setIcon)(icon, "sparkles");
    this.element.appendChild(icon);
    document.body.appendChild(this.element);
  }
  update(settings) {
    this.element?.toggleClass("is-hidden", !settings.profileCardEnabled);
    this.element?.toggleClass("is-compact", settings.compactDashboard);
  }
  unmount() {
    this.element?.remove();
    this.element = null;
  }
};
var WidgetManager = class {
  constructor(plugin) {
    this.widgets = [
      new StatusBarWidget(plugin),
      new BannerWidget(),
      new QuoteWidget(),
      new ProfileCardWidget()
    ];
  }
  mount() {
    this.widgets.forEach((widget) => widget.mount());
  }
  update(settings) {
    this.widgets.forEach((widget) => widget.update(settings));
  }
  unmount() {
    this.widgets.forEach((widget) => widget.unmount());
  }
};

// src/modules.ts
var WidgetModule = class {
  constructor(plugin) {
    this.widgetManager = new WidgetManager(plugin);
  }
  mount() {
    this.widgetManager.mount();
  }
  update(settings) {
    this.widgetManager.update(settings);
  }
  unmount() {
    this.widgetManager.unmount();
  }
};
var DashboardModule = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.panelView = null;
  }
  mount() {
    this.plugin.registerView(MIKU_PANEL_VIEW, (leaf) => {
      this.panelView = new MikuPanelView(leaf, this.getSettings());
      return this.panelView;
    });
  }
  update(settings) {
    const leaves = this.plugin.app.workspace.getLeavesOfType(MIKU_PANEL_VIEW);
    if (leaves.length > 0) {
      const view = leaves[0]?.view;
      if (view instanceof MikuPanelView) {
        view.setSettings(settings);
      }
    } else if (this.panelView) {
      this.panelView.setSettings(settings);
    }
  }
  unmount() {
    this.plugin.app.workspace.detachLeavesOfType(MIKU_PANEL_VIEW);
    this.panelView = null;
  }
  getSettings() {
    const plugin = this.plugin;
    return plugin.settings ?? {
      themeMode: "MinimalMiku",
      statusBarEnabled: true,
      bannerEnabled: false,
      quoteEnabled: false,
      quoteIntervalSeconds: 25,
      profileCardEnabled: false,
      compactDashboard: false,
      glowIntensity: 0.55,
      reducedMotion: false,
      bannerText: "Miku Mode Active"
    };
  }
};
var ModuleRegistry = class {
  constructor(plugin) {
    this.modules = [new WidgetModule(plugin), new DashboardModule(plugin)];
  }
  async mountAll() {
    for (const module2 of this.modules) {
      await module2.mount();
    }
  }
  async updateAll(settings) {
    for (const module2 of this.modules) {
      await module2.update(settings);
    }
  }
  async unmountAll() {
    for (const module2 of this.modules) {
      await module2.unmount();
    }
  }
};

// src/theme-manager.ts
var ROOT_CLASS = "miku-plugin-enabled";
var ThemeManager = class {
  apply(settings) {
    document.body.classList.add(ROOT_CLASS);
    document.body.dataset.mikuTheme = settings.themeMode;
    document.body.dataset.mikuReducedMotion = settings.reducedMotion ? "true" : "false";
    document.body.style.setProperty("--miku-glow-intensity", String(settings.glowIntensity));
  }
  cleanup() {
    document.body.classList.remove(ROOT_CLASS);
    delete document.body.dataset.mikuTheme;
    delete document.body.dataset.mikuReducedMotion;
    document.body.style.removeProperty("--miku-glow-intensity");
  }
};

// src/main.ts
var MikuPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.themeManager = new ThemeManager();
    this.moduleRegistry = null;
    this.dashboardLeaf = null;
  }
  async onload() {
    await this.loadPluginSettings();
    this.themeManager.apply(this.settings);
    this.moduleRegistry = new ModuleRegistry(this);
    await this.moduleRegistry.mountAll();
    await this.moduleRegistry.updateAll(this.settings);
    this.addRibbonIcon("sparkles", "Open Miku dashboard", () => {
      void this.openDashboardView();
    });
    this.addCommand({
      id: "miku-cycle-theme",
      name: "Cycle Miku theme mode",
      callback: async () => {
        await this.cycleTheme();
      }
    });
    this.addCommand({
      id: "miku-open-dashboard",
      name: "Open Miku dashboard",
      callback: async () => {
        await this.openDashboardView();
      }
    });
    this.addSettingTab(new MikuSettingTab(this.app, this));
  }
  onunload() {
    void this.moduleRegistry?.unmountAll();
    this.moduleRegistry = null;
    this.dashboardLeaf = null;
    this.themeManager.cleanup();
  }
  async saveAndRefresh() {
    await this.saveData(this.settings);
    this.themeManager.apply(this.settings);
    await this.moduleRegistry?.updateAll(this.settings);
    const openView = this.dashboardLeaf?.view;
    if (openView instanceof MikuPanelView) {
      openView.setSettings(this.settings);
    }
  }
  async loadPluginSettings() {
    const loaded = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...loaded ?? {} };
  }
  async cycleTheme() {
    const modes = ["MinimalMiku", "Concert", "NightNeon", "SnowMiku"];
    const index = modes.indexOf(this.settings.themeMode);
    const next = modes[(index + 1) % modes.length];
    this.settings.themeMode = next;
    await this.saveAndRefresh();
    new import_obsidian4.Notice(`Miku theme switched to ${next}`);
  }
  async openDashboardView() {
    this.dashboardLeaf = this.app.workspace.getLeavesOfType(MIKU_PANEL_VIEW)[0] ?? null;
    if (!this.dashboardLeaf) {
      this.dashboardLeaf = this.app.workspace.getRightLeaf(false);
      await this.dashboardLeaf?.setViewState({
        type: MIKU_PANEL_VIEW,
        active: true
      });
    }
    if (this.dashboardLeaf) {
      this.app.workspace.revealLeaf(this.dashboardLeaf);
      const view = this.dashboardLeaf.view;
      if (view instanceof MikuPanelView) {
        view.setSettings(this.settings);
      }
    }
  }
};
